export const FETCH_CURRENT_WEATHER = 'FETCH_CURRENT_WEATHER';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_POSITION = 'GET_CURRENT_POSITION';
export const GET_CURRENT_POSITION_SUCCESS = 'GET_CURRENT_POSITION_SUCCESS';
export const GET_CURRENT_POSITION_FAILED = 'GET_CURRENT_POSITION_FAILED';
